FROM debian:testing

ENV DEBIAN_FRONTEND noninteractive

ARG gosu_ver=1.10

# Instruction:
# - go to https://github.com/ClickHouse/ClickHouse/commits/master
# - get last sha for which build passed already,
#   **and don't use commits from PRs only from master**
# - update ch_sha (full SHA)
# - update ch_version (example: 20.5.1.3627)
ARG ch_sha=5f99d887ccc235c6c177ccbf5f96292806f5a0d7
ARG ch_version=20.5.1.3649

RUN apt-get update \
    && apt-get update \
    && apt-get install --allow-unauthenticated --yes --no-install-recommends \
           locales \
           tzdata \
           ca-certificates \
           wget \
    && true

RUN \
    ch_url=https://clickhouse-builds.s3.yandex.net/0/$ch_sha/clang-10_relwithdebuginfo_address_bundled_unsplitted_disable_False_deb && \
    ch_packages="clickhouse-client_$ch_version+asan_all.deb clickhouse-common-static_$ch_version+asan_amd64.deb clickhouse-server_$ch_version+asan_all.deb" && \
    echo $ch_packages | tr ' ' '\n' | xargs -t -i -n1 wget -q $ch_url/{}
RUN dpkg -i *.deb

ADD https://github.com/tianon/gosu/releases/download/$gosu_ver/gosu-amd64 /bin/gosu

# locales
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    dpkg-reconfigure locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN mkdir /docker-entrypoint-initdb.d

COPY clickhouse-server/docker_related_config.xml /etc/clickhouse-server/config.d/
COPY clickhouse-server/entrypoint.sh /entrypoint.sh

RUN chmod +x \
    /entrypoint.sh \
    /bin/gosu

EXPOSE 9000 8123 9009
VOLUME /var/lib/clickhouse

ENV CLICKHOUSE_CONFIG /etc/clickhouse-server/config.xml

ENTRYPOINT ["/entrypoint.sh"]
