---
# TODO: split asan and asan-dbg
name: dockerimage-ch-clickhouse-server-asan
on:
  push:
    paths:
      - ch/Dockerfile.clickhouse-server-asan
      - ch/Dockerfile.clickhouse-server-asan-dbg
      - .github/workflows/dockerimage-clickhouse-server-asan.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/Push clickhouse-server-asan
        run: |
          registry=docker.pkg.github.com
          name=$registry/$GITHUB_REPOSITORY/clickhouse-server-asan
          echo "Image: $name (on behalf of $GITHUB_ACTOR)"

          docker login $registry --username $GITHUB_ACTOR --password $DOCKER_PASS
          docker build ch --file ch/Dockerfile.clickhouse-server-asan --tag $name
          docker push $name
        env:
          DOCKER_PASS: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build/Push clickhouse-server-asan-dbg
        run: |
          registry=docker.pkg.github.com
          name=$registry/$GITHUB_REPOSITORY/clickhouse-server-asan-dbg
          echo "Image: $name (on behalf of $GITHUB_ACTOR)"

          docker login $registry --username $GITHUB_ACTOR --password $DOCKER_PASS
          docker build ch --file ch/Dockerfile.clickhouse-server-asan-dbg --tag $name
          docker push $name
        env:
          DOCKER_PASS: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
